services:
  db:
    image: postgres:16
    container_name: ecommerce-db
    env_file:
      - .env.dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ecommerce-backend
    env_file:
      - .env.dev
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend/ecommerce-frontend
    container_name: ecommerce-frontend
    env_file:
      - .env.dev
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
